import "websocket-polyfill";
import {
  nip05,
  nip19,
  getEventHash,
  signEvent,
  type Event,
  relayInit,
} from "nostr-tools";

export const DEFAULT_RELAYS = [
  "wss://relay.damus.io",
  "wss://relay.snort.social",
  "wss://nostr.wine",
  "wss://eden.nostr.land",
  "wss://relay.orangepill.dev",
  "wss://nostr.fmt.wiz.biz",
  "wss://nostr.milou.lol",
];

export const CONTENT_PREFIX = "Description generated by ChatGPT for #[0]:\n\n";

export const isNpub = (value: string) =>
  /npub1[acdefghjklmnpqrstuvwxyz023456789]{58}/.test(value);

export const getPubkeyAndRelays = async (value: string) => {
  try {
    if (isNpub(value)) {
      const pubkey = nip19.decode(value).data as string;
      const relays: { relay: string; read: boolean; write: boolean }[] =
        await fetch(`/api/users/${pubkey}/relays`).then((res) => res.json());
      const readRelays = relays
        .filter(({ read }) => read)
        .map(({ relay }) => relay);

      return { pubkey, relays: readRelays ?? DEFAULT_RELAYS };
    }

    const res = await nip05.queryProfile(value);

    if (!res?.pubkey) {
      throw new Error("No pubkey found for this nip-05");
    }

    return { pubkey: res.pubkey, relays: res?.relays ?? DEFAULT_RELAYS };
  } catch (error) {
    alert(error instanceof Error ? error.message : "something went wrong :(");
  }
};

interface DescriptionNoost {
  userPubkey: string; // hex
  frenstrPubkey: string; // hex
  frenstrPrivkey: string; // hex
  content: string;
}

export const createDescriptionNoost = ({
  userPubkey,
  frenstrPubkey,
  frenstrPrivkey,
  content,
}: DescriptionNoost) => {
  const baseEvent = {
    kind: 1,
    pubkey: frenstrPubkey,
    created_at: Math.floor(Date.now() / 1000),
    tags: [["p", userPubkey]],
    content: `${CONTENT_PREFIX}${content}`,
  };
  const eventWithId = { ...baseEvent, id: getEventHash(baseEvent) };

  return { ...eventWithId, sig: signEvent(eventWithId, frenstrPrivkey) };
};

export const publishNoost = async (
  event: Event
): Promise<{ success: boolean; message: string }> => {
  const relay = relayInit(
    process.env.PUBLISH_RELAY ?? "wss://nostr.mutinywallet.com"
  );

  try {
    relay.on("connect", () => {
      console.log(`connected`);
    });
    relay.on("error", () => {
      console.log(`failed`);
    });

    await relay.connect();

    let pub = relay.publish(event);
    return await new Promise((resolve, reject) => {
      pub.on("ok", () => {
        resolve({
          success: true,
          message: `${relay.url} has accepted our event`,
        });
      });
      pub.on("failed", (reason: string) => {
        reject(new Error(`failed to publish to ${relay.url}: ${reason}`));
      });
    });
  } catch (error) {
    return {
      success: false,
      message:
        error instanceof Error ? error.message : "Something went wrong :(",
    };
  } finally {
    if (relay) {
      try {
        relay.close();
      } catch {
        // fail silently for errors that happen when closing the pool
      }
    }
  }
};
